AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ChronosFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
      SamResourceId: ChronosFunction
    Properties:
      Runtime: provided.al2
      Handler: bootstrap
      CodeUri: ChronosFunction
      Environment:
        Variables:
          DATABASE_DSN: ''
          JWT_SECRET: ''
          CRYPTO_KEY: ''
          LOCAL_TEST: 'false'
          GOOGLE_CLIENT_ID: ''
          GOOGLE_CLIENT_SECRET: ''
          GOOGLE_REDIRECT_URL: ''
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
